:ext-relative:
:toc: macro
:toclevels: 4

# Wren Playground

A simple playground for playing with https://wren.io[Wren]

++++
<video src="https://user-images.githubusercontent.com/292738/117061815-a11b9500-acf0-11eb-9361-ec8c5704766a.mp4">
++++

## Components

### Imports

- `import "!{{module}}`" for Module`: Imports from built-in modules.
- `import "~{{module}}" for Module`: Imports from `HOME` directory.
- `import "#{{module}}" for Module`: Imports from `.wren` directory.

### Constants

There are a few constants:

- `%{date.iso}`: Returns the current ISO 8601 date
- `%{date.unix}`: Returns the unix timestamp in milliseconds
- `%{~}`: Returns the path to user's `HOME` directory
- `%{#}`: Returns the path to `.wren` directory

### Modules

Modules from https://rosettacode.org/wiki/Category:Wren[Rosetta Wren] have been built-in
to complement _Wren CLI_ standard modules. Import them using `!{{module name}}`.
Example `import "!fmt" for Fmt`

- fmt
- str
- sort
- math
- trait
- seq
- date
- rat
- pattern
- big
- upc
- matrix
- set
- llist
- queue
- complex
- dynamic
- ioutil
- long

### Custom Wren CLI

You can override the custom `wren_cli` used. Just put a `wren` or `wren.exe` in your `.wren` directory.

### .wren directory

Is a directory where you can store a custom `wren_cli` or scripts.
Normally is located in `HOME`. `~/.wren`.

Example: `/Users/clsource/.wren`

## 📘 LICENSE
MIT

## 🤩 Credits

++++
<p>
  Made with <i class="fa fa-heart">&#9829;</i> by
  <a href="https://ninjas.cl">
    Ninjas.cl
  </a>.
</p>
++++
